version: '3.7'
services:
  # Backend service
  mysql_5.7:
    image: mysql:5.7
    volumes:
      - ./database/fineract-db/docker:/docker-entrypoint-initdb.d:Z,ro
      - ./database/db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "--password=mysql" ]
      timeout: 10s
      retries: 10
    ports:
      - "3306:3306"
  postgres_14.1_alpine:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'



   